[build]
  command = "composer install --no-dev"
  publish = "."

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[build.environment]
  PHP_VERSION = "8.1"
